name: usage_example
version: 0.0.1
description: A sample demonstrating the usage package and Flutter.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/collinjackson/usage_example

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  usage: any
